/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.PageGUI.tblMeetings;
import static GUI.PageGUI.tblMeetingsDecide;
import Objects.CurrentDM;
import Objects.CurrentUser;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import methods.DecideMeeting;
import methods.SuggestMeeting;

/**
 *
 * @author pierre
 */
public class DecideMeetingGUI extends javax.swing.JFrame {
    


    /**
     * Creates new form VoteMeetingGUI
     */
    public DecideMeetingGUI() {
        initComponents();
        groupButton();
        rbMeeting1.setVisible(false);
        rbMeeting2.setVisible(false);
        rbMeeting3.setVisible(false);
    }

    public void setMeetingName(String meetingName) {
        lblMeetingName.setText(meetingName);
        taDescriptionMeeting.setText(CurrentDM.currentDM.getDescription());
    }
    
    
    
    public void setComboBox(int numberOfProposals){
        
        System.out.println("setComboBox " + numberOfProposals);
        if(numberOfProposals == 1){
        rbMeeting1.setVisible(true);
        
        } else if(numberOfProposals == 2){
        rbMeeting1.setVisible(true);
        rbMeeting2.setVisible(true);
        
        } else if(numberOfProposals == 3){
        rbMeeting1.setVisible(true);
        rbMeeting2.setVisible(true);
        rbMeeting3.setVisible(true);
        
        }
    
    }
    
    private void groupButton( ) {

    ButtonGroup bgDMG = new ButtonGroup( );

bgDMG.add(rbMeeting1);
bgDMG.add(rbMeeting2);
bgDMG.add(rbMeeting3);

}
    
    public boolean noneSelected(){
        boolean noneSelected = false;
    if(!rbMeeting1.isSelected() && !rbMeeting2.isSelected() && !rbMeeting3.isSelected()){
    noneSelected = true;
    }
    return noneSelected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVMRubrik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMeetingProposes = new javax.swing.JTable();
        btnSendChoices = new javax.swing.JToggleButton();
        lblMeetingName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescriptionMeeting = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        rbMeeting1 = new javax.swing.JRadioButton();
        rbMeeting2 = new javax.swing.JRadioButton();
        rbMeeting3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVMRubrik.setText("Fastställ mötestid utifrån antalet röster här nedan och fyll i en beskrivning.");
        jPanel1.add(lblVMRubrik, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 24, -1, -1));

        jScrollPane1.setBorder(null);

        tblMeetingProposes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Datum", "Starttid", "Sluttid", "Antal röster"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMeetingProposes.setRowHeight(26);
        jScrollPane1.setViewportView(tblMeetingProposes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 87, -1, 100));

        btnSendChoices.setText("Boka mötet");
        btnSendChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendChoicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSendChoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        lblMeetingName.setText("Mötes Namn");
        jPanel1.add(lblMeetingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        taDescriptionMeeting.setColumns(20);
        taDescriptionMeeting.setLineWrap(true);
        taDescriptionMeeting.setRows(5);
        jScrollPane2.setViewportView(taDescriptionMeeting);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 219, 450, 70));

        jLabel1.setText("Beskrivning:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        rbMeeting1.setText("Fastställ");
        jPanel1.add(rbMeeting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        rbMeeting2.setText("Fastställ");
        rbMeeting2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMeeting2ActionPerformed(evt);
            }
        });
        jPanel1.add(rbMeeting2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        rbMeeting3.setText("Fastställ");
        rbMeeting3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMeeting3ActionPerformed(evt);
            }
        });
        jPanel1.add(rbMeeting3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendChoicesActionPerformed
        if(!noneSelected()){
            CurrentDM.currentDM.decideSpecificMeeting();
        
        JOptionPane.showMessageDialog(null, "Mötet är fastställt och de inbjudna har blivit inbokade");
        CurrentDM.currentDM.fillMeetingDecideTable(tblMeetingsDecide);

        dispose();
        } else {
           int jopAnswer = JOptionPane.showConfirmDialog((Component) null, "Är du säker på att du inte vill fastställa någon av tiderna?", "", JOptionPane.YES_NO_OPTION);
            if(jopAnswer == 0){
        dispose();
            }
        }
 
    }//GEN-LAST:event_btnSendChoicesActionPerformed

    private void rbMeeting2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMeeting2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMeeting2ActionPerformed

    private void rbMeeting3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMeeting3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMeeting3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSendChoices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMeetingName;
    private javax.swing.JLabel lblVMRubrik;
    public static javax.swing.JRadioButton rbMeeting1;
    public static javax.swing.JRadioButton rbMeeting2;
    public static javax.swing.JRadioButton rbMeeting3;
    public static javax.swing.JTextArea taDescriptionMeeting;
    public static javax.swing.JTable tblMeetingProposes;
    // End of variables declaration//GEN-END:variables
}
