/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Objects.CurrentComments;
import Objects.CurrentUser;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.border.Border;
import methods.FetchComments;

/**
 *
 * @author pierre
 */
public class PostGUI extends javax.swing.JFrame {

    private String[] messages = {};
    private int msgCounter = 0;
//    public static JPanel panel;
    private JScrollPane scrollPane;
    private Timer timer;
    private ResultSet rs = null;
    public static JFrame frame;
    public static int postID;
    public static String publisher;
    public static String title;
    public static String postText;
    public static String user;
    public static boolean admin;

    /**
     * Creates new form PostGUI
     */
    public PostGUI(int postID, String publisher, String title, String postText) {
        
        this.postID = postID;
        this.publisher = publisher;
        this.title = title;
        this.postText = postText;
        
        initComponents();
     new FetchComments(postID);
     btnPGUppdateraPost.setVisible(false);
     btnPGRedigera.setVisible(false);
     
     if(CurrentUser.currentUser.isAdmin() || CurrentUser.currentUser.getName().equals(publisher)){
         btnPGRedigera.setVisible(true);
     }
     
     //CurrentUser.currentUser.isAdmin();
     //CurrentUser.currentUser.getName();
    }
    
        public static void addMessage(String text) {
//        boolean oddMessage = msgCounter % 2 != 0;
//        Color color = oddMessage ? Color.WHITE : Color.GRAY;

        JTextArea label = new JTextArea(text);
        label.setMaximumSize(new java.awt.Dimension(600, 600));
        label.setLineWrap(true);
        label.setOpaque(true);
        label.setBackground(new java.awt.Color(158, 174, 187));
//        label.setBackground(color);
        Border border = BorderFactory.createLineBorder(new java.awt.Color(77,85,92));
        label.setBorder(BorderFactory.createCompoundBorder(border, BorderFactory.createEmptyBorder(10, 10, 10, 10)));

//    JPanel panelBox = new JPanel();
//    panelBox.setLayout(new BoxLayout(panelBox, BoxLayout.X_AXIS));
//    panelBox.setBorder(BorderFactory.createEmptyBorder(2,4,2,4));
        panelBox.add(label);
//    panel.add(panelBox);
//    panel.revalidate();
//    msgCounter++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taPostText = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelBox = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        lblUniversitet = new javax.swing.JLabel();
        lblOrebro = new javax.swing.JLabel();
        iconLogga = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        btnPGComment = new javax.swing.JButton();
        btnPGRedigera = new javax.swing.JButton();
        btnPGUppdateraPost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(10000, 10000));

        jPanel1.setBackground(new java.awt.Color(77, 85, 92));

        taPostText.setEditable(false);
        taPostText.setBackground(new java.awt.Color(158, 174, 187));
        taPostText.setColumns(20);
        taPostText.setForeground(new java.awt.Color(77, 85, 92));
        taPostText.setLineWrap(true);
        taPostText.setRows(5);
        taPostText.setText(postText);
        taPostText.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taPostText);

        lblTitle.setBackground(new java.awt.Color(158, 174, 187));
        lblTitle.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(158, 174, 187));
        lblTitle.setText(title);

        jScrollPane1.setBackground(new java.awt.Color(158, 174, 187));
        jScrollPane1.setAutoscrolls(true);

        panelBox.setBackground(new java.awt.Color(158, 174, 187));
        panelBox.setAlignmentY(0.0F);
        panelBox.setLayout(new javax.swing.BoxLayout(panelBox, javax.swing.BoxLayout.Y_AXIS));

        panel.setBackground(new java.awt.Color(158, 174, 187));
        panel.setToolTipText("");
        panel.setRequestFocusEnabled(false);
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.LINE_AXIS));
        panelBox.add(panel);
        panel.getAccessibleContext().setAccessibleName("");

        jScrollPane1.setViewportView(panelBox);

        lblUniversitet.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        lblUniversitet.setForeground(new java.awt.Color(202, 100, 91));
        lblUniversitet.setText("Örebro");

        lblOrebro.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        lblOrebro.setForeground(new java.awt.Color(202, 100, 91));
        lblOrebro.setText("Universitet");

        iconLogga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logga.png"))); // NOI18N

        lblAuthor.setBackground(new java.awt.Color(158, 174, 187));
        lblAuthor.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        lblAuthor.setForeground(new java.awt.Color(158, 174, 187));
        lblAuthor.setText(publisher);

        btnPGComment.setBackground(new java.awt.Color(202, 100, 91));
        btnPGComment.setForeground(new java.awt.Color(158, 174, 187));
        btnPGComment.setText("Kommentera");
        btnPGComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPGCommentActionPerformed(evt);
            }
        });

        btnPGRedigera.setBackground(new java.awt.Color(202, 100, 91));
        btnPGRedigera.setForeground(new java.awt.Color(158, 174, 187));
        btnPGRedigera.setText("Redigera Post");
        btnPGRedigera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPGRedigeraActionPerformed(evt);
            }
        });

        btnPGUppdateraPost.setBackground(new java.awt.Color(202, 100, 91));
        btnPGUppdateraPost.setForeground(new java.awt.Color(158, 174, 187));
        btnPGUppdateraPost.setText("Uppdatera Post");
        btnPGUppdateraPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPGUppdateraPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconLogga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUniversitet)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblOrebro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPGComment, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle)
                                    .addComponent(lblAuthor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPGRedigera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPGUppdateraPost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUniversitet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrebro)
                            .addComponent(btnPGComment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPGRedigera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPGUppdateraPost))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(iconLogga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPGCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPGCommentActionPerformed
        // TODO add your handling code here:
        new CommentGUI(postID).setVisible(true);
    }//GEN-LAST:event_btnPGCommentActionPerformed

    private void btnPGRedigeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPGRedigeraActionPerformed
        // TODO add your handling code here:
        taPostText.setEditable(true);
        btnPGUppdateraPost.setVisible(true);
    }//GEN-LAST:event_btnPGRedigeraActionPerformed

    private void btnPGUppdateraPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPGUppdateraPostActionPerformed
        // TODO add your handling code here:
        try{
        String newText = taPostText.getText();
        Statement st = Connectivity.ConnectionClass.conn.createStatement();
        String query = "UPDATE `Inlägg` SET Text = '"+newText+"' where Titel = '"+title+"';";
        st.execute(query);
        
        btnPGUppdateraPost.setVisible(false);
        btnPGRedigera.setEnabled(false);
        taPostText.setEditable(false);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPGUppdateraPostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostGUI(postID, publisher, title, postText).setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPGComment;
    private javax.swing.JButton btnPGRedigera;
    private javax.swing.JButton btnPGUppdateraPost;
    private javax.swing.JLabel iconLogga;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblOrebro;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniversitet;
    public static javax.swing.JPanel panel;
    public static javax.swing.JPanel panelBox;
    private javax.swing.JTextArea taPostText;
    // End of variables declaration//GEN-END:variables
}
