/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.PageGUI.tblMeetings;
import Objects.CurrentUser;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import methods.SuggestMeeting;

/**
 *
 * @author pierre
 */
public class VoteMeetingGUI extends javax.swing.JFrame {

    /**
     * Creates new form VoteMeetingGUI
     */
    public VoteMeetingGUI() {
        initComponents();
        cbMeeting1.setVisible(false);
        cbMeeting2.setVisible(false);
        cbMeeting3.setVisible(false);
    }

    public void setMeetingName(String meetingName) {
        lblMeetingName.setText(meetingName);
    }
    
    
    
    public void setComboBox(int numberOfProposals){
        
        System.out.println("setComboBox " + numberOfProposals);
        if(numberOfProposals == 1){
        cbMeeting1.setVisible(true);
        
        } else if(numberOfProposals == 2){
        cbMeeting1.setVisible(true);
        cbMeeting2.setVisible(true);
        
        } else if(numberOfProposals == 3){
        cbMeeting1.setVisible(true);
        cbMeeting2.setVisible(true);
        cbMeeting3.setVisible(true);
        
        }
    
    }
    
    public boolean noneSelected(){
        boolean noneSelected = false;
    if(!cbMeeting1.isSelected() && !cbMeeting2.isSelected() && !cbMeeting3.isSelected()){
    noneSelected = true;
    }
    return noneSelected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVMRubrik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMeetingProposes = new javax.swing.JTable();
        cbMeeting1 = new javax.swing.JCheckBox();
        cbMeeting2 = new javax.swing.JCheckBox();
        cbMeeting3 = new javax.swing.JCheckBox();
        btnSendChoices = new javax.swing.JToggleButton();
        lblMeetingName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVMRubrik.setText("Rösta på de mötestförslag som passar dig för mötet:");
        jPanel1.add(lblVMRubrik, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 24, -1, -1));

        tblMeetingProposes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Datum", "Starttid", "Sluttid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMeetingProposes.setRowHeight(23);
        jScrollPane1.setViewportView(tblMeetingProposes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 87, -1, 91));

        cbMeeting1.setText("Ja");
        jPanel1.add(cbMeeting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 106, -1, -1));

        cbMeeting2.setText("Ja");
        jPanel1.add(cbMeeting2, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 132, -1, -1));

        cbMeeting3.setText("Ja");
        jPanel1.add(cbMeeting3, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 158, -1, -1));

        btnSendChoices.setText("Skicka val");
        btnSendChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendChoicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSendChoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 206, -1, -1));

        lblMeetingName.setText("Mötes Namn");
        jPanel1.add(lblMeetingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendChoicesActionPerformed
        if(!noneSelected()){
        SuggestMeeting.voteMeeting();
        SuggestMeeting.deleteFromProposes();        
        SuggestMeeting h = new SuggestMeeting();
        h.showSuggestedMeetings(tblMeetings, CurrentUser.currentUser.getID());
        
        JOptionPane.showMessageDialog(null, "Dina godkända mötestider är skickade till mötesinbokaren");
        dispose();
        } else {
           int jopAnswer = JOptionPane.showConfirmDialog((Component) null, "Är du säker på att du inte vill acceptera någon av tiderna?", "", JOptionPane.YES_NO_OPTION);
            if(jopAnswer == 0){
        SuggestMeeting.deleteFromProposes();        
        SuggestMeeting h = new SuggestMeeting();
        h.showSuggestedMeetings(tblMeetings, CurrentUser.currentUser.getID());
        dispose();
            }
        }
 
    }//GEN-LAST:event_btnSendChoicesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSendChoices;
    public static javax.swing.JCheckBox cbMeeting1;
    public static javax.swing.JCheckBox cbMeeting2;
    public static javax.swing.JCheckBox cbMeeting3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMeetingName;
    private javax.swing.JLabel lblVMRubrik;
    public static javax.swing.JTable tblMeetingProposes;
    // End of variables declaration//GEN-END:variables
}
